export type AlertStatus = 'success' | 'error' | 'info' | 'warning';
export type CaseType = 'ray_x' | 'ecography' | 'tac' | 'mri' | 'laboratory' | 'other';
export type ColumnOrderDto = {
order: number;
field_name: string;
showing: boolean;
};
export type FileData = {
name: string;
size: string;
type: string;
url: string;
id: string | null;
uuid: string | null;
collection_name: string | null;
disk: string | null;
};
export type FormUIMap = 'users' | 'doctors' | 'patients' | 'cases' | 'case_reviews' | 'invoices' | 'payments';
export type InvoiceStatus = 'draft' | 'issued' | 'partially_paid' | 'paid' | 'refunded' | 'overdue' | 'canceled';
export type MaritalStatus = 'single' | 'married' | 'divorced' | 'widowed';
export type PatientCaseStatus = 'submitted' | 'awaiting_assignment' | 'assigned' | 'under_review' | 'reviewed' | 'in_secondary_review' | 'secondary_reviewed' | 'closed' | 'reopened' | 'cancelled';
export type PersonDto = {
name: string;
last_name: string;
gender: Sex;
marital_status: MaritalStatus;
middle_name: string | null;
birth_date: any | string | null;
nationality: string | null;
province: string | null;
city: string | null;
postal_code: string | null;
address_one: string | null;
address_two: string | null;
address_three: string | null;
address_four: string | null;
phone_one: string | null;
phone_two: string | null;
phone_three: string | null;
phone_four: string | null;
death_date: any | string | null;
cause_of_death: string | null;
};
export type ReviewStatus = 'pending' | 'in_progress' | 'completed';
export type Sex = 'male' | 'female' | 'other';
export type Urgency = 'low' | 'normal' | 'emergency' | 'critical';
export type UserDto = {
name: string;
email: string;
password: string | null;
};
